sudo: required
services: 
  - docker

before_install:
  - docker build -t phanisamples/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true phanisamples/docker-react npm run test -- --coverage
